In [1]:
import os
import sys
import pandas as pd
from pathlib import Path
import ast
import geopandas as gpd
import numpy as np
import matplotlib.pyplot as plt
import gc

# Change root directory to the repo root (Jupyter: __file__ is not defined)
def find_repo_root(start=Path.cwd()):
	for p in [start] + list(start.parents):
		if (p / 'Code').exists() or (p / '.git').exists() or (p / 'local_repo').exists():
			return p
	return start

repo_root = find_repo_root()
data_root = repo_root.parent.parent / 'Data' / 'CBOS ready'
geo_root = repo_root.parent.parent / 'Data' / 'Geospatial'
gus_root = Path(os.getcwd()).parent.parent.parent.parent / "Data" / "GUS"

os.chdir(repo_root)
sys.path.append(str(repo_root / 'Code' / 'tools'))

# import local toolkit (try normal import first, fall back to loading from file)
try:
	import inequality_analyzers as inqA
	import local_utility_functions as luf
except Exception:
	import importlib.util
	toolkit_path = repo_root / 'Code' / 'tools' / 'inequality_analyzers.py'
	if toolkit_path.exists():
		spec = importlib.util.spec_from_file_location("inequality_analyzers", str(toolkit_path))
		stk = importlib.util.module_from_spec(spec)
		spec.loader.exec_module(stk)
	else:
		raise

In [2]:
df_demographic = pd.read_csv(gus_root / "data" / 'bdl_demographic_data.csv', encoding='utf-8')
df_variables = pd.read_csv(gus_root / "metadata" / 'bdl_variables_level6.csv', encoding='utf-8')

In [3]:
def process_subject_data(subjectId):
    """
    Process demographic data for a given subject ID.
    Returns expanded dataframe with flattened structure.
    """
    # Filter by subjectId
    df_subject = df_demographic[df_demographic['subjectId'] == subjectId]
    
    # Get variable metadata for this subject
    variable_ids = df_subject['variableId'].unique()
    df_variables_subset = df_variables[df_variables['id'].isin(variable_ids)][['id', 'n1', 'n2', 'n3', 'n4', 'n5']]
    
    # Merge subject data with variables
    df_merged = pd.merge(df_subject, df_variables_subset, left_on='variableId', right_on='id', how='left')
    
    # Remove constant columns
    for col in ['n1', 'n2', 'n3', 'n4', 'n5']:
        if df_merged[col].nunique() <= 1:
            df_merged = df_merged.drop(columns=[col])
    
    # Parse values column
    def parse_values_column(value):
        try:
            value_list = ast.literal_eval(value)
            if isinstance(value_list, list) and len(value_list) == 1:
                return value_list[0]
            return value_list
        except (ValueError, SyntaxError):
            return None
    
    df_merged['values'] = df_merged['values'].apply(parse_values_column)
    
    # Expand and normalize
    df_expanded = df_merged.explode('values').reset_index(drop=True)
    values_normalized = pd.json_normalize(df_expanded['values'])
    df_expanded = pd.concat([df_expanded.drop(columns=['values']), values_normalized], axis=1)
    
    # Rename and format columns
    df_expanded = df_expanded.rename(columns={"id_x": "nuts_id", "id_y": "var_id"})
    df_expanded['nuts_id'] = df_expanded['nuts_id'].apply(lambda x: str(int(x)).zfill(12))
    df_expanded['teryt_id'] = df_expanded['nuts_id'].apply(luf.nuts_code_to_teryt)
    
    return df_expanded

In [4]:
df_var = {}
#subjects = list(set(df_demographic['subjectId']))
subjects = ['P2137']
for subject in subjects:
    df_var[subject] = process_subject_data(subject)
    df_var[subject]['teryt_id'] = df_var[subject]['nuts_id'].apply(luf.nuts_code_to_teryt)

gc.collect()

286

In [5]:
df_var['P2137']

,nuts_id,name,variableId,subjectId,var_id,n1,n2,year,val,attrId,teryt_id
0,000000000000,POLSKA,72305,P2137,72305,ogółem,ogółem,1995,38609399.0,1.0,0000000
1,000000000000,POLSKA,72305,P2137,72305,ogółem,ogółem,1996,38639341.0,1.0,0000000
2,000000000000,POLSKA,72305,P2137,72305,ogółem,ogółem,1997,38659979.0,1.0,0000000
3,000000000000,POLSKA,72305,P2137,72305,ogółem,ogółem,1998,38666983.0,1.0,0000000
4,000000000000,POLSKA,72305,P2137,72305,ogółem,ogółem,1999,38263303.0,1.0,0000000
...,...,...,...,...,...,...,...,...,...,...,...
7369075,071427338054,Wiskitki - miasto,454046,P2137,454046,0-14,kobiety,2024,123.0,1.0,1438054
7369076,071427338055,Wiskitki - obszar wiejski,454046,P2137,454046,0-14,kobiety,2021,701.0,1.0,1438055
7369077,071427338055,Wiskitki - obszar wiejski,454046,P2137,454046,0-14,kobiety,2022,704.0,1.0,1438055
7369078,071427338055,Wiskitki - obszar wiejski,454046,P2137,454046,0-14,kobiety,2023,686.0,1.0,1438055
7369079,071427338055,Wiskitki - obszar wiejski,454046,P2137,454046,0-14,kobiety,2024,670.0,1.0,1438055

In [6]:
df_census_1988 = pd.read_csv(gus_root / "data" / "census_data" / 'NSP1988_data.csv', encoding='utf-8')
df_census_2002 = pd.read_csv(gus_root / "data" / "census_data" / 'NSP2002_data.csv', encoding='utf-8')
df_census_2011 = pd.read_csv(gus_root / "data" / "census_data" / 'NSP2011_data.csv', encoding='utf-8')
df_census_2021 = pd.read_csv(gus_root / "data" / "census_data" / 'NSP2021_data.csv', encoding='utf-8')

df_census = {}
df_census[1988] = df_census_1988
df_census[2002] = df_census_2002
df_census[2011] = df_census_2011
df_census[2021] = df_census_2021

subjects = []
variables = []

for key in df_census.keys():
    subjects.append(list(df_census[key]['subjectId'].unique()))
    variables.append(list(df_census[key]['variableId'].unique()))
    
subjects = [v for var in subjects for v in var]
variables = [str(v) for var in variables for v in var]

In [7]:
print(subjects)
print(variables)

['P2884', 'P2885', 'P2883', 'P2887', 'P2114', 'P2403', 'P2402', 'P2871', 'P3304', 'P3311', 'P3309', 'P3310', 'P3420', 'P4253', 'P4320', 'P4345', 'P4287']
['196133', '196134', '196135', '196136', '196137', '196138', '196139', '196140', '196142', '196143', '196144', '196145', '196130', '196131', '196132', '196149', '196150', '196151', '196152', '9476', '9482', '9488', '9494', '9500', '9506', '9512', '9518', '9524', '9530', '9536', '9542', '9548', '9554', '9560', '9566', '9572', '9616', '9622', '9628', '9634', '9640', '9646', '9652', '9658', '9664', '9670', '9676', '9682', '9688', '9694', '9700', '9706', '9712', '9720', '9726', '9732', '9738', '9744', '9750', '9756', '9762', '9768', '9774', '9780', '9786', '9792', '9798', '9804', '9810', '9816', '46503', '46509', '46517', '60475', '60476', '60477', '60379', '60380', '60381', '60382', '60383', '60384', '60385', '60386', '60387', '60388', '60389', '60390', '60391', '60392', '60393', '60394', '60395', '60396', '60397', '60398', '60399', '60400', '60401', '60402', '60403', '60404', '60405', '60406', '60407', '60408', '60409', '60410', '60411', '60412', '60413', '60414', '60415', '60416', '60417', '60418', '60419', '60420', '60421', '60422', '60423', '60424', '60425', '60426', '60428', '60429', '60430', '60431', '60432', '60433', '60434', '60436', '60437', '60438', '60439', '60440', '60441', '60442', '60443', '60444', '60445', '60446', '60447', '60448', '60449', '60450', '60451', '60452', '60453', '60454', '60455', '60456', '60457', '60458', '60459', '60460', '60461', '60462', '60463', '60464', '60465', '60466', '60467', '60468', '60469', '60470', '60471', '60472', '60473', '60474', '60355', '60356', '60357', '60358', '60359', '60360', '60361', '60362', '60363', '60364', '60365', '60366', '60367', '60368', '60369', '60370', '60371', '60372', '60373', '60374', '60375', '60376', '60377', '60378', '194829', '194830', '194831', '194832', '194833', '194834', '194835', '194836', '194837', '194838', '194839', '194840', '395983', '395984', '395985', '395986', '395987', '395988', '395989', '395990', '395991', '395992', '395993', '395994', '395995', '395996', '395997', '395998', '395999', '396000', '396001', '396002', '396003', '396004', '396005', '396006', '396007', '396008', '396009', '396010', '396011', '396012', '396013', '396014', '396015', '396016', '396017', '396018', '396019', '396020', '396021', '396022', '396023', '396024', '396025', '396026', '396027', '396028', '396029', '396030', '396031', '396032', '396033', '396034', '396035', '396036', '396037', '396038', '396039', '396040', '396041', '396042', '396112', '396113', '396114', '396115', '396116', '396117', '396118', '396119', '396120', '396121', '396122', '396123', '396124', '396125', '396126', '396127', '396128', '396129', '396130', '396131', '396132', '396133', '396134', '396135', '396136', '396137', '396138', '396139', '396140', '396141', '396142', '396143', '396144', '396145', '396146', '396147', '396148', '396149', '396150', '396151', '396152', '396153', '396154', '396155', '396156', '396157', '396158', '396159', '396160', '396161', '396162', '396163', '396164', '396165', '396166', '396167', '396168', '396169', '396170', '396171', '396172', '396173', '396174', '396175', '396176', '396177', '396178', '396179', '396180', '396181', '396182', '396183', '396184', '396185', '396186', '396187', '396188', '396189', '396190', '396191', '396192', '396193', '396194', '396195', '396196', '396197', '396198', '396199', '396200', '396201', '396202', '396203', '396204', '396205', '396206', '396207', '396208', '396209', '396210', '396211', '396212', '396213', '396214', '396215', '396216', '396217', '396218', '396219', '396220', '396221', '396222', '396223', '396224', '396225', '396226', '396227', '396228', '396058', '396059', '396060', '396061', '396062', '396063', '396064', '396065', '396066', '396067', '396068', '396069', '396070', '396071', '396072', '396073', '396074', '396076', '396077', '396078', '396075', '396079', '396080', '396081', '396082', '396083', '396084', '396085', '396086', '396087', '396088', '396089', '396090', '396091', '396092', '396093', '396094', '396095', '396096', '396097', '396098', '396099', '396100', '396101', '396102', '396103', '396104', '396105', '396106', '396107', '396108', '396109', '396110', '396111', '450464', '450465', '450466', '450467', '450468', '450469', '450470', '450471', '450472', '450473', '450474', '450475', '450476', '450477', '450478', '450479', '1644511', '1644512', '1644513', '1644514', '1644515', '1644516', '1644517', '1644518', '1644519', '1644520', '1644521', '1644522', '1644523', '1644524', '1644525', '1644526', '1644527', '1644528', '1644529', '1644530', '1644531', '1644532', '1644533', '1644534', '1644535', '1644536', '1644537', '1644538', '1644539', '1644540', '1644541', '1644542', '1644543', '1644544', '1644545', '1644546', '1644547', '1644548', '1644549', '1644550', '1644551', '1644552', '1644553', '1644554', '1644555', '1644556', '1644557', '1644558', '1644559', '1644560', '1644561', '1644562', '1644563', '1644564', '1644565', '1644566', '1644567', '1644568', '1644569', '1644570', '1701450', '1701451', '1701452', '1701453', '1701454', '1701455', '1701456', '1701457', '1701458', '1701459', '1701460', '1701461', '1701462', '1701463', '1701464', '1701465', '1701466', '1701467', '1701468', '1701469', '1701470', '1701471', '1701472', '1701473', '1701474', '1701475', '1701476', '1701477', '1701478', '1701479', '1701480', '1701481', '1701482', '1701483', '1701484', '1701485', '1701486', '1701487', '1701488', '1701489', '1701490', '1701491', '1701492', '1701493', '1701494', '1701495', '1701496', '1701497', '1701498', '1701499', '1701500', '1701501', '1701502', '1701503', '1701504', '1701505', '1701506', '1701507', '1701508', '1701509', '1701510', '1701511', '1701512', '1701513', '1701514', '1701515', '1701516', '1701517', '1701518', '1701519', '1701520', '1701521', '1701522', '1701523', '1701524', '1701525', '1701526', '1701527', '1701528', '1701529', '1701530', '1701531', '1701532', '1701533', '1701534', '1701535', '1701536', '1701537', '1701538', '1701539', '1701540', '1701541', '1701542', '1701543', '1701544', '1701545', '1701546', '1701547', '1701548', '1701549', '1701550', '1701551', '1701552', '1701553', '1701554', '1701555', '1701556', '1701557', '1703330', '1703331', '1703332', '1703333', '1703334', '1703335', '1703336', '1703337', '1703338', '1703339', '1703340', '1703341', '1703342', '1703343', '1703344', '1703345', '1703346', '1703347', '1703348', '1703349', '1703350', '1703351', '1703352', '1703353', '1703354', '1703355', '1703356', '1703357', '1703358', '1703359', '1703360', '1703361', '1703362', '1703363', '1703364', '1703365', '1703366', '1703367', '1703368', '1703369', '1703370', '1703371', '1703372', '1703373', '1703374', '1703375', '1703376', '1703377', '1703378', '1703379', '1703380', '1703381', '1703382', '1703383', '1703384', '1703385', '1703386', '1703387', '1703388', '1703389', '1703390', '1703391', '1703392', '1703393', '1703394', '1703395', '1703396', '1703397', '1703398', '1703399', '1703400', '1703401', '1703402', '1703403', '1703404', '1703405', '1703406', '1703407', '1703408', '1703409', '1703410', '1703411', '1703412', '1703413', '1703414', '1703415', '1703416', '1703417', '1703418', '1703419', '1703420', '1703421', '1703422', '1703423', '1703424', '1703425', '1703426', '1703427', '1703428', '1703429', '1703430', '1703431', '1703432', '1703433', '1703434', '1703435', '1703436', '1703437', '1703438', '1703439', '1703440', '1703441', '1703442', '1703443', '1703444', '1703445', '1703446', '1703447', '1703448', '1703449', '1703450', '1703451', '1703452', '1703453', '1703454', '1703455', '1652549', '1652550', '1652551', '1652552', '1652553', '1652554', '1652555', '1652556']

In [8]:
# Set up API
# API key: c2ccd182-be71-41ee-6a99-08de61444905
# Another: 1de25faa-0796-4036-6a9c-08de61444905
# Another: 80b20037-8e82-42ec-6a9f-08de61444905
# Another: a2dbb3a9-026c-4aa5-6aa0-08de61444905
# Another: ed928d84-8050-4861-6aa1-08de61444905

import requests
from pandas import json_normalize
import time

#API_KEYS = ['1de25faa-0796-4036-6a9c-08de61444905', '80b20037-8e82-42ec-6a9f-08de61444905', 'a2dbb3a9-026c-4aa5-6aa0-08de61444905', 'ed928d84-8050-4861-6aa1-08de61444905', 'c2ccd182-be71-41ee-6a99-08de61444905']
API_KEYS = ["01fa8599-3e8c-48ef-6aa2-08de61444905"]

API_BASE = "https://bdl.stat.gov.pl/api/v1"
API_KEY = API_KEYS[0]
# os.getenv("BDL_API_KEY")  # optional: export BDL_API_KEY to raise rate limits

HEADERS = {"User-Agent": "LRDWI-Notebook/1.0"}
if API_KEY:
    HEADERS["X-ClientId"] = API_KEY

OUTPUT_DIR = gus_root / "metadata"

# Install nest_asyncio if not available
try:
    import nest_asyncio
except ImportError:
    import subprocess
    import sys
    subprocess.check_call([sys.executable, "-m", "pip", "install", "nest_asyncio", "aiohttp"])
    import nest_asyncio

In [11]:
# Jupyter-ready cell: download variable meta
# Produces: bdl_variables_level6.csv (full metadata returned by the API, flattened)
# Run this cell as-is. Optional: set API_KEY to your X-ClientId to raise rate limits.

# Install deps (uncomment if needed)
# %pip install requests pandas

ENDPOINT = f"{API_BASE}/variables"

session = requests.Session()
session.headers.update(HEADERS)

rows = []

print("Fetching variables (server-side filter: level=6)...")
i=1
for var in variables:
    params = {
        "format": "json",
        "lang": "pl"
    }
    endpoint = ENDPOINT + f"/{var}"
    print(endpoint)
    r = session.get(endpoint,params= params, timeout=30)
    r.raise_for_status()
    js = r.json()
    
    rows.append(js)
    print(f"Fetched variable {i}/{len(variables)}: {var}")
    time.sleep(0.25)
    i+=1


df = pd.DataFrame(rows)

# reorder some useful columns if present
cols_pref = [c for c in ["id","name","level","measureUnitId","measureUnitName","subjectId","subjectName"] if c in df.columns]
other_cols = [c for c in df.columns if c not in cols_pref]
df = df[cols_pref + other_cols]

# quick preview
df

# Save to CSV
output_path = OUTPUT_DIR / "census_meta.csv"
df.to_csv(output_path, index=False, encoding='utf-8')

Fetching variables (server-side filter: level=6)...
https://bdl.stat.gov.pl/api/v1/variables/196133
Fetched variable 1/755: 196133
https://bdl.stat.gov.pl/api/v1/variables/196134
Fetched variable 2/755: 196134
https://bdl.stat.gov.pl/api/v1/variables/196135
Fetched variable 3/755: 196135
https://bdl.stat.gov.pl/api/v1/variables/196136
Fetched variable 4/755: 196136
https://bdl.stat.gov.pl/api/v1/variables/196137
Fetched variable 5/755: 196137
https://bdl.stat.gov.pl/api/v1/variables/196138
Fetched variable 6/755: 196138
https://bdl.stat.gov.pl/api/v1/variables/196139
Fetched variable 7/755: 196139
https://bdl.stat.gov.pl/api/v1/variables/196140
Fetched variable 8/755: 196140
https://bdl.stat.gov.pl/api/v1/variables/196142
Fetched variable 9/755: 196142
https://bdl.stat.gov.pl/api/v1/variables/196143
Fetched variable 10/755: 196143
https://bdl.stat.gov.pl/api/v1/variables/196144
Fetched variable 11/755: 196144
https://bdl.stat.gov.pl/api/v1/variables/196145
Fetched variable 12/755: 196145
https://bdl.stat.gov.pl/api/v1/variables/196130
Fetched variable 13/755: 196130
https://bdl.stat.gov.pl/api/v1/variables/196131
Fetched variable 14/755: 196131
https://bdl.stat.gov.pl/api/v1/variables/196132
Fetched variable 15/755: 196132
https://bdl.stat.gov.pl/api/v1/variables/196149
Fetched variable 16/755: 196149
https://bdl.stat.gov.pl/api/v1/variables/196150
Fetched variable 17/755: 196150
https://bdl.stat.gov.pl/api/v1/variables/196151
Fetched variable 18/755: 196151
https://bdl.stat.gov.pl/api/v1/variables/196152
Fetched variable 19/755: 196152
https://bdl.stat.gov.pl/api/v1/variables/9476
Fetched variable 20/755: 9476
https://bdl.stat.gov.pl/api/v1/variables/9482
Fetched variable 21/755: 9482
https://bdl.stat.gov.pl/api/v1/variables/9488
Fetched variable 22/755: 9488
https://bdl.stat.gov.pl/api/v1/variables/9494
Fetched variable 23/755: 9494
https://bdl.stat.gov.pl/api/v1/variables/9500
Fetched variable 24/755: 9500
https://bdl.stat.gov.pl/api/v1/variables/9506
Fetched variable 25/755: 9506
https://bdl.stat.gov.pl/api/v1/variables/9512
Fetched variable 26/755: 9512
https://bdl.stat.gov.pl/api/v1/variables/9518
Fetched variable 27/755: 9518
https://bdl.stat.gov.pl/api/v1/variables/9524
Fetched variable 28/755: 9524
https://bdl.stat.gov.pl/api/v1/variables/9530
Fetched variable 29/755: 9530
https://bdl.stat.gov.pl/api/v1/variables/9536
Fetched variable 30/755: 9536
https://bdl.stat.gov.pl/api/v1/variables/9542
Fetched variable 31/755: 9542
https://bdl.stat.gov.pl/api/v1/variables/9548
Fetched variable 32/755: 9548
https://bdl.stat.gov.pl/api/v1/variables/9554
Fetched variable 33/755: 9554
https://bdl.stat.gov.pl/api/v1/variables/9560
Fetched variable 34/755: 9560
https://bdl.stat.gov.pl/api/v1/variables/9566
Fetched variable 35/755: 9566
https://bdl.stat.gov.pl/api/v1/variables/9572
Fetched variable 36/755: 9572
https://bdl.stat.gov.pl/api/v1/variables/9616
Fetched variable 37/755: 9616
https://bdl.stat.gov.pl/api/v1/variables/9622
Fetched variable 38/755: 9622
https://bdl.stat.gov.pl/api/v1/variables/9628
Fetched variable 39/755: 9628
https://bdl.stat.gov.pl/api/v1/variables/9634
Fetched variable 40/755: 9634
https://bdl.stat.gov.pl/api/v1/variables/9640
Fetched variable 41/755: 9640
https://bdl.stat.gov.pl/api/v1/variables/9646
Fetched variable 42/755: 9646
https://bdl.stat.gov.pl/api/v1/variables/9652
Fetched variable 43/755: 9652
https://bdl.stat.gov.pl/api/v1/variables/9658
Fetched variable 44/755: 9658
https://bdl.stat.gov.pl/api/v1/variables/9664
Fetched variable 45/755: 9664
https://bdl.stat.gov.pl/api/v1/variables/9670
Fetched variable 46/755: 9670
https://bdl.stat.gov.pl/api/v1/variables/9676
Fetched variable 47/755: 9676
https://bdl.stat.gov.pl/api/v1/variables/9682
Fetched variable 48/755: 9682
https://bdl.stat.gov.pl/api/v1/variables/9688
Fetched variable 49/755: 9688
https://bdl.stat.gov.pl/api/v1/variables/9694
Fetched variable 50/755: 9694
https://bdl.stat.gov.pl/api/v1/variables/9700
Fetched variable 51/755: 9700
https://bdl.stat.gov.pl/api/v1/variables/9706
Fetched variable 52/755: 9706
https://bdl.stat.gov.pl/api/v1/variables/9712
Fetched variable 53/755: 9712
https://bdl.stat.gov.pl/api/v1/variables/9720
Fetched variable 54/755: 9720
https://bdl.stat.gov.pl/api/v1/variables/9726
Fetched variable 55/755: 9726
https://bdl.stat.gov.pl/api/v1/variables/9732
Fetched variable 56/755: 9732
https://bdl.stat.gov.pl/api/v1/variables/9738
Fetched variable 57/755: 9738
https://bdl.stat.gov.pl/api/v1/variables/9744
Fetched variable 58/755: 9744
https://bdl.stat.gov.pl/api/v1/variables/9750
Fetched variable 59/755: 9750
https://bdl.stat.gov.pl/api/v1/variables/9756
Fetched variable 60/755: 9756
https://bdl.stat.gov.pl/api/v1/variables/9762
Fetched variable 61/755: 9762
https://bdl.stat.gov.pl/api/v1/variables/9768
Fetched variable 62/755: 9768
https://bdl.stat.gov.pl/api/v1/variables/9774
Fetched variable 63/755: 9774
https://bdl.stat.gov.pl/api/v1/variables/9780
Fetched variable 64/755: 9780
https://bdl.stat.gov.pl/api/v1/variables/9786
Fetched variable 65/755: 9786
https://bdl.stat.gov.pl/api/v1/variables/9792
Fetched variable 66/755: 9792
https://bdl.stat.gov.pl/api/v1/variables/9798
Fetched variable 67/755: 9798
https://bdl.stat.gov.pl/api/v1/variables/9804
Fetched variable 68/755: 9804
https://bdl.stat.gov.pl/api/v1/variables/9810
Fetched variable 69/755: 9810
https://bdl.stat.gov.pl/api/v1/variables/9816
Fetched variable 70/755: 9816
https://bdl.stat.gov.pl/api/v1/variables/46503
Fetched variable 71/755: 46503
https://bdl.stat.gov.pl/api/v1/variables/46509
Fetched variable 72/755: 46509
https://bdl.stat.gov.pl/api/v1/variables/46517
Fetched variable 73/755: 46517
https://bdl.stat.gov.pl/api/v1/variables/60475
Fetched variable 74/755: 60475
https://bdl.stat.gov.pl/api/v1/variables/60476
Fetched variable 75/755: 60476
https://bdl.stat.gov.pl/api/v1/variables/60477
Fetched variable 76/755: 60477
https://bdl.stat.gov.pl/api/v1/variables/60379
Fetched variable 77/755: 60379
https://bdl.stat.gov.pl/api/v1/variables/60380
Fetched variable 78/755: 60380
https://bdl.stat.gov.pl/api/v1/variables/60381
Fetched variable 79/755: 60381
https://bdl.stat.gov.pl/api/v1/variables/60382
Fetched variable 80/755: 60382
https://bdl.stat.gov.pl/api/v1/variables/60383
Fetched variable 81/755: 60383
https://bdl.stat.gov.pl/api/v1/variables/60384
Fetched variable 82/755: 60384
https://bdl.stat.gov.pl/api/v1/variables/60385
Fetched variable 83/755: 60385
https://bdl.stat.gov.pl/api/v1/variables/60386
Fetched variable 84/755: 60386
https://bdl.stat.gov.pl/api/v1/variables/60387
Fetched variable 85/755: 60387
https://bdl.stat.gov.pl/api/v1/variables/60388
Fetched variable 86/755: 60388
https://bdl.stat.gov.pl/api/v1/variables/60389
Fetched variable 87/755: 60389
https://bdl.stat.gov.pl/api/v1/variables/60390
Fetched variable 88/755: 60390
https://bdl.stat.gov.pl/api/v1/variables/60391
Fetched variable 89/755: 60391
https://bdl.stat.gov.pl/api/v1/variables/60392
Fetched variable 90/755: 60392
https://bdl.stat.gov.pl/api/v1/variables/60393
Fetched variable 91/755: 60393
https://bdl.stat.gov.pl/api/v1/variables/60394
Fetched variable 92/755: 60394
https://bdl.stat.gov.pl/api/v1/variables/60395
Fetched variable 93/755: 60395
https://bdl.stat.gov.pl/api/v1/variables/60396
Fetched variable 94/755: 60396
https://bdl.stat.gov.pl/api/v1/variables/60397
Fetched variable 95/755: 60397
https://bdl.stat.gov.pl/api/v1/variables/60398
Fetched variable 96/755: 60398
https://bdl.stat.gov.pl/api/v1/variables/60399
Fetched variable 97/755: 60399
https://bdl.stat.gov.pl/api/v1/variables/60400
Fetched variable 98/755: 60400
https://bdl.stat.gov.pl/api/v1/variables/60401
Fetched variable 99/755: 60401
https://bdl.stat.gov.pl/api/v1/variables/60402
Fetched variable 100/755: 60402
https://bdl.stat.gov.pl/api/v1/variables/60403
Fetched variable 101/755: 60403
https://bdl.stat.gov.pl/api/v1/variables/60404
Fetched variable 102/755: 60404
https://bdl.stat.gov.pl/api/v1/variables/60405
Fetched variable 103/755: 60405
https://bdl.stat.gov.pl/api/v1/variables/60406
Fetched variable 104/755: 60406
https://bdl.stat.gov.pl/api/v1/variables/60407
Fetched variable 105/755: 60407
https://bdl.stat.gov.pl/api/v1/variables/60408
Fetched variable 106/755: 60408
https://bdl.stat.gov.pl/api/v1/variables/60409
Fetched variable 107/755: 60409
https://bdl.stat.gov.pl/api/v1/variables/60410
Fetched variable 108/755: 60410
https://bdl.stat.gov.pl/api/v1/variables/60411
Fetched variable 109/755: 60411
https://bdl.stat.gov.pl/api/v1/variables/60412
Fetched variable 110/755: 60412
https://bdl.stat.gov.pl/api/v1/variables/60413
Fetched variable 111/755: 60413
https://bdl.stat.gov.pl/api/v1/variables/60414
Fetched variable 112/755: 60414
https://bdl.stat.gov.pl/api/v1/variables/60415
Fetched variable 113/755: 60415
https://bdl.stat.gov.pl/api/v1/variables/60416
Fetched variable 114/755: 60416
https://bdl.stat.gov.pl/api/v1/variables/60417
Fetched variable 115/755: 60417
https://bdl.stat.gov.pl/api/v1/variables/60418
Fetched variable 116/755: 60418
https://bdl.stat.gov.pl/api/v1/variables/60419
Fetched variable 117/755: 60419
https://bdl.stat.gov.pl/api/v1/variables/60420
Fetched variable 118/755: 60420
https://bdl.stat.gov.pl/api/v1/variables/60421
Fetched variable 119/755: 60421
https://bdl.stat.gov.pl/api/v1/variables/60422
Fetched variable 120/755: 60422
https://bdl.stat.gov.pl/api/v1/variables/60423
Fetched variable 121/755: 60423
https://bdl.stat.gov.pl/api/v1/variables/60424
Fetched variable 122/755: 60424
https://bdl.stat.gov.pl/api/v1/variables/60425
Fetched variable 123/755: 60425
https://bdl.stat.gov.pl/api/v1/variables/60426
Fetched variable 124/755: 60426
https://bdl.stat.gov.pl/api/v1/variables/60428
Fetched variable 125/755: 60428
https://bdl.stat.gov.pl/api/v1/variables/60429
Fetched variable 126/755: 60429
https://bdl.stat.gov.pl/api/v1/variables/60430
Fetched variable 127/755: 60430
https://bdl.stat.gov.pl/api/v1/variables/60431
Fetched variable 128/755: 60431
https://bdl.stat.gov.pl/api/v1/variables/60432
Fetched variable 129/755: 60432
https://bdl.stat.gov.pl/api/v1/variables/60433
Fetched variable 130/755: 60433
https://bdl.stat.gov.pl/api/v1/variables/60434
Fetched variable 131/755: 60434
https://bdl.stat.gov.pl/api/v1/variables/60436
Fetched variable 132/755: 60436
https://bdl.stat.gov.pl/api/v1/variables/60437
Fetched variable 133/755: 60437
https://bdl.stat.gov.pl/api/v1/variables/60438
Fetched variable 134/755: 60438
https://bdl.stat.gov.pl/api/v1/variables/60439
Fetched variable 135/755: 60439
https://bdl.stat.gov.pl/api/v1/variables/60440
Fetched variable 136/755: 60440
https://bdl.stat.gov.pl/api/v1/variables/60441
Fetched variable 137/755: 60441
https://bdl.stat.gov.pl/api/v1/variables/60442
Fetched variable 138/755: 60442
https://bdl.stat.gov.pl/api/v1/variables/60443
Fetched variable 139/755: 60443
https://bdl.stat.gov.pl/api/v1/variables/60444
Fetched variable 140/755: 60444
https://bdl.stat.gov.pl/api/v1/variables/60445
Fetched variable 141/755: 60445
https://bdl.stat.gov.pl/api/v1/variables/60446
Fetched variable 142/755: 60446
https://bdl.stat.gov.pl/api/v1/variables/60447
Fetched variable 143/755: 60447
https://bdl.stat.gov.pl/api/v1/variables/60448
Fetched variable 144/755: 60448
https://bdl.stat.gov.pl/api/v1/variables/60449
Fetched variable 145/755: 60449
https://bdl.stat.gov.pl/api/v1/variables/60450
Fetched variable 146/755: 60450
https://bdl.stat.gov.pl/api/v1/variables/60451
Fetched variable 147/755: 60451
https://bdl.stat.gov.pl/api/v1/variables/60452
Fetched variable 148/755: 60452
https://bdl.stat.gov.pl/api/v1/variables/60453
Fetched variable 149/755: 60453
https://bdl.stat.gov.pl/api/v1/variables/60454
Fetched variable 150/755: 60454
https://bdl.stat.gov.pl/api/v1/variables/60455
Fetched variable 151/755: 60455
https://bdl.stat.gov.pl/api/v1/variables/60456
Fetched variable 152/755: 60456
https://bdl.stat.gov.pl/api/v1/variables/60457
Fetched variable 153/755: 60457
https://bdl.stat.gov.pl/api/v1/variables/60458
Fetched variable 154/755: 60458
https://bdl.stat.gov.pl/api/v1/variables/60459
Fetched variable 155/755: 60459
https://bdl.stat.gov.pl/api/v1/variables/60460
Fetched variable 156/755: 60460
https://bdl.stat.gov.pl/api/v1/variables/60461
Fetched variable 157/755: 60461
https://bdl.stat.gov.pl/api/v1/variables/60462
Fetched variable 158/755: 60462
https://bdl.stat.gov.pl/api/v1/variables/60463
Fetched variable 159/755: 60463
https://bdl.stat.gov.pl/api/v1/variables/60464
Fetched variable 160/755: 60464
https://bdl.stat.gov.pl/api/v1/variables/60465
Fetched variable 161/755: 60465
https://bdl.stat.gov.pl/api/v1/variables/60466
Fetched variable 162/755: 60466
https://bdl.stat.gov.pl/api/v1/variables/60467
Fetched variable 163/755: 60467
https://bdl.stat.gov.pl/api/v1/variables/60468
Fetched variable 164/755: 60468
https://bdl.stat.gov.pl/api/v1/variables/60469
Fetched variable 165/755: 60469
https://bdl.stat.gov.pl/api/v1/variables/60470
Fetched variable 166/755: 60470
https://bdl.stat.gov.pl/api/v1/variables/60471
Fetched variable 167/755: 60471
https://bdl.stat.gov.pl/api/v1/variables/60472
Fetched variable 168/755: 60472
https://bdl.stat.gov.pl/api/v1/variables/60473
Fetched variable 169/755: 60473
https://bdl.stat.gov.pl/api/v1/variables/60474
Fetched variable 170/755: 60474
https://bdl.stat.gov.pl/api/v1/variables/60355
Fetched variable 171/755: 60355
https://bdl.stat.gov.pl/api/v1/variables/60356
Fetched variable 172/755: 60356
https://bdl.stat.gov.pl/api/v1/variables/60357
Fetched variable 173/755: 60357
https://bdl.stat.gov.pl/api/v1/variables/60358
Fetched variable 174/755: 60358
https://bdl.stat.gov.pl/api/v1/variables/60359
Fetched variable 175/755: 60359
https://bdl.stat.gov.pl/api/v1/variables/60360
Fetched variable 176/755: 60360
https://bdl.stat.gov.pl/api/v1/variables/60361
Fetched variable 177/755: 60361
https://bdl.stat.gov.pl/api/v1/variables/60362
Fetched variable 178/755: 60362
https://bdl.stat.gov.pl/api/v1/variables/60363
Fetched variable 179/755: 60363
https://bdl.stat.gov.pl/api/v1/variables/60364
Fetched variable 180/755: 60364
https://bdl.stat.gov.pl/api/v1/variables/60365
Fetched variable 181/755: 60365
https://bdl.stat.gov.pl/api/v1/variables/60366
Fetched variable 182/755: 60366
https://bdl.stat.gov.pl/api/v1/variables/60367
Fetched variable 183/755: 60367
https://bdl.stat.gov.pl/api/v1/variables/60368
Fetched variable 184/755: 60368
https://bdl.stat.gov.pl/api/v1/variables/60369
Fetched variable 185/755: 60369
https://bdl.stat.gov.pl/api/v1/variables/60370
Fetched variable 186/755: 60370
https://bdl.stat.gov.pl/api/v1/variables/60371
Fetched variable 187/755: 60371
https://bdl.stat.gov.pl/api/v1/variables/60372
Fetched variable 188/755: 60372
https://bdl.stat.gov.pl/api/v1/variables/60373
Fetched variable 189/755: 60373
https://bdl.stat.gov.pl/api/v1/variables/60374
Fetched variable 190/755: 60374
https://bdl.stat.gov.pl/api/v1/variables/60375
Fetched variable 191/755: 60375
https://bdl.stat.gov.pl/api/v1/variables/60376
Fetched variable 192/755: 60376
https://bdl.stat.gov.pl/api/v1/variables/60377
Fetched variable 193/755: 60377
https://bdl.stat.gov.pl/api/v1/variables/60378
Fetched variable 194/755: 60378
https://bdl.stat.gov.pl/api/v1/variables/194829
Fetched variable 195/755: 194829
https://bdl.stat.gov.pl/api/v1/variables/194830
Fetched variable 196/755: 194830
https://bdl.stat.gov.pl/api/v1/variables/194831
Fetched variable 197/755: 194831
https://bdl.stat.gov.pl/api/v1/variables/194832
Fetched variable 198/755: 194832
https://bdl.stat.gov.pl/api/v1/variables/194833
Fetched variable 199/755: 194833
https://bdl.stat.gov.pl/api/v1/variables/194834
Fetched variable 200/755: 194834
https://bdl.stat.gov.pl/api/v1/variables/194835
Fetched variable 201/755: 194835
https://bdl.stat.gov.pl/api/v1/variables/194836
Fetched variable 202/755: 194836
https://bdl.stat.gov.pl/api/v1/variables/194837
Fetched variable 203/755: 194837
https://bdl.stat.gov.pl/api/v1/variables/194838
Fetched variable 204/755: 194838
https://bdl.stat.gov.pl/api/v1/variables/194839
Fetched variable 205/755: 194839
https://bdl.stat.gov.pl/api/v1/variables/194840
Fetched variable 206/755: 194840
https://bdl.stat.gov.pl/api/v1/variables/395983
Fetched variable 207/755: 395983
https://bdl.stat.gov.pl/api/v1/variables/395984
Fetched variable 208/755: 395984
https://bdl.stat.gov.pl/api/v1/variables/395985
Fetched variable 209/755: 395985
https://bdl.stat.gov.pl/api/v1/variables/395986
Fetched variable 210/755: 395986
https://bdl.stat.gov.pl/api/v1/variables/395987
Fetched variable 211/755: 395987
https://bdl.stat.gov.pl/api/v1/variables/395988
Fetched variable 212/755: 395988
https://bdl.stat.gov.pl/api/v1/variables/395989
Fetched variable 213/755: 395989
https://bdl.stat.gov.pl/api/v1/variables/395990
Fetched variable 214/755: 395990
https://bdl.stat.gov.pl/api/v1/variables/395991
Fetched variable 215/755: 395991
https://bdl.stat.gov.pl/api/v1/variables/395992
Fetched variable 216/755: 395992
https://bdl.stat.gov.pl/api/v1/variables/395993
Fetched variable 217/755: 395993
https://bdl.stat.gov.pl/api/v1/variables/395994
Fetched variable 218/755: 395994
https://bdl.stat.gov.pl/api/v1/variables/395995
Fetched variable 219/755: 395995
https://bdl.stat.gov.pl/api/v1/variables/395996
Fetched variable 220/755: 395996
https://bdl.stat.gov.pl/api/v1/variables/395997
Fetched variable 221/755: 395997
https://bdl.stat.gov.pl/api/v1/variables/395998
Fetched variable 222/755: 395998
https://bdl.stat.gov.pl/api/v1/variables/395999
Fetched variable 223/755: 395999
https://bdl.stat.gov.pl/api/v1/variables/396000
Fetched variable 224/755: 396000
https://bdl.stat.gov.pl/api/v1/variables/396001
Fetched variable 225/755: 396001
https://bdl.stat.gov.pl/api/v1/variables/396002
Fetched variable 226/755: 396002
https://bdl.stat.gov.pl/api/v1/variables/396003
Fetched variable 227/755: 396003
https://bdl.stat.gov.pl/api/v1/variables/396004
Fetched variable 228/755: 396004
https://bdl.stat.gov.pl/api/v1/variables/396005
Fetched variable 229/755: 396005
https://bdl.stat.gov.pl/api/v1/variables/396006
Fetched variable 230/755: 396006
https://bdl.stat.gov.pl/api/v1/variables/396007
Fetched variable 231/755: 396007
https://bdl.stat.gov.pl/api/v1/variables/396008
Fetched variable 232/755: 396008
https://bdl.stat.gov.pl/api/v1/variables/396009
Fetched variable 233/755: 396009
https://bdl.stat.gov.pl/api/v1/variables/396010
Fetched variable 234/755: 396010
https://bdl.stat.gov.pl/api/v1/variables/396011
Fetched variable 235/755: 396011
https://bdl.stat.gov.pl/api/v1/variables/396012
Fetched variable 236/755: 396012
https://bdl.stat.gov.pl/api/v1/variables/396013
Fetched variable 237/755: 396013
https://bdl.stat.gov.pl/api/v1/variables/396014
Fetched variable 238/755: 396014
https://bdl.stat.gov.pl/api/v1/variables/396015
Fetched variable 239/755: 396015
https://bdl.stat.gov.pl/api/v1/variables/396016
Fetched variable 240/755: 396016
https://bdl.stat.gov.pl/api/v1/variables/396017
Fetched variable 241/755: 396017
https://bdl.stat.gov.pl/api/v1/variables/396018
Fetched variable 242/755: 396018
https://bdl.stat.gov.pl/api/v1/variables/396019
Fetched variable 243/755: 396019
https://bdl.stat.gov.pl/api/v1/variables/396020
Fetched variable 244/755: 396020
https://bdl.stat.gov.pl/api/v1/variables/396021
Fetched variable 245/755: 396021
https://bdl.stat.gov.pl/api/v1/variables/396022
Fetched variable 246/755: 396022
https://bdl.stat.gov.pl/api/v1/variables/396023
Fetched variable 247/755: 396023
https://bdl.stat.gov.pl/api/v1/variables/396024
Fetched variable 248/755: 396024
https://bdl.stat.gov.pl/api/v1/variables/396025
Fetched variable 249/755: 396025
https://bdl.stat.gov.pl/api/v1/variables/396026
Fetched variable 250/755: 396026
https://bdl.stat.gov.pl/api/v1/variables/396027
Fetched variable 251/755: 396027
https://bdl.stat.gov.pl/api/v1/variables/396028
Fetched variable 252/755: 396028
https://bdl.stat.gov.pl/api/v1/variables/396029
Fetched variable 253/755: 396029

In [ ]:
df

,id,level,measureUnitId,measureUnitName,subjectId,n1,years,n2,n3
0,196133,7,26,osoba,P2884,ogółem,[1998],NaN,NaN
1,196134,7,26,osoba,P2884,0-9,[1998],NaN,NaN
2,196135,7,26,osoba,P2884,10-19,[1998],NaN,NaN
3,196136,7,26,osoba,P2884,20-29,[1998],NaN,NaN
4,196137,7,26,osoba,P2884,30-39,[1998],NaN,NaN
...,...,...,...,...,...,...,...,...,...
750,1652552,6,37,gosp.,P4287,gospodarstwa domowe 3-osobowe,[2021],NaN,NaN
751,1652553,6,37,gosp.,P4287,gospodarstwa domowe 4-osobowe,[2021],NaN,NaN
752,1652554,6,37,gosp.,P4287,gospodarstwa domowe 5-osobowe i większe,[2021],NaN,NaN
753,1652555,6,26,osoba,P4287,ludność w gospodarstwach domowych,[2021],NaN,NaN
754,1652556,6,26,osoba,P4287,przeciętna liczba osób w gospodarstwie domowym,[2021],NaN,NaN

In [ ]:
df_census_2002['subjectId'].unique()

In [ ]:
print(df_census_1988['subjectId'].unique())
print(df_census_1988['variableId'].unique())

In [ ]:
temp = pd.DataFrame({"id": [196133, 196134, 196135, 196136, 196137, 196138, 196139, 196140, ],
                     "level": [6,6,6,6,6,6,6,6, ],
                     "measureUnitId": [26,26,26,26,26,26,26,26,],
                     "measureUnitName": ["osoba","osoba","osoba","osoba","osoba","osoba","osoba","osoba",],
                     "subjectId": ["P2884","P2884","P2884","P2884","P2884","P2884","P2884","P2884",],
                     "n1": ["ogółem", "0-9", "10-19", "20-29", "30-39", "40-49", "50-59", "60 lat i więcej",],
                     "n2": [],
                     "n3": [],
                     "n4": [],
                     "n5": [],})

In [ ]:
df_variables[df_variables['subjectId'] == "P2114"]